### ISSUE TITLE
Debian + php

### ISSUE THREAD

**Issue by DarkZeroCD** [cactus/go-camo#17]
Hello,

Can your solution run on a dedicated Debian-based server? A script in php is it easy to write?
If possible, do you think you can help me?
This is to replace the atmos/camo solution

Thank you in advance

**Comment by cactus** [comment]
There should be no problem running go-camo on a debian server. The linux binary should function just fine.

As for php, there is a php library named [camo-url-generator](https://github.com/jdreesen/camo-url-generator) that may work for you (no personal experience using it).

However, if you already use atmos/camo, there honestly shouldn't be much work you need to do, aside from getting go-camo itself running. go-camo is mostly compatible -- just make sure you use "path format" urls and not "query string format" urls.

Unfortunately, I don't have time to assist you with general setup or configuration, beyond pointing out that some information is already documented in the README and man pages.

**Comment by DarkZeroCD** [comment]
Ok, thanks for the information, I thought go-camo was more powerful and stable. If it's the same thing, no need to change it.

**Comment by cactus** [comment]
The differences are [outlined in the readme](https://github.com/cactus/go-camo#differences-from-camo). I think it has quite a few improvements over atmos/camo. I simply said it should be, more or less, a drop in replacement.

Closing ticket.
