### ISSUE TITLE
Build instructions not complete

### ISSUE THREAD

**Issue by viraptor** [cactus/go-camo#23]
### Specifications

Please list the go-camo version, as well as the Operation System (and version)
that go-camo is running on. The go-camo version can be found by `go-camo -V`.

Version: git master
Platform: macos 10.13

### Expected Behavior

go-camo compiles

### Actual Behavior
```
package github.com/cactus/go-camo: no Go files in /tmp/go/src/github.com/cactus/go-camo
```
### Steps to reproduce

Follow the README instructions:
```
➜  ~ export GOPATH=/tmp/go
➜  ~ go get -d github.com/cactus/go-camo
package github.com/cactus/go-camo: no Go files in /tmp/go/src/github.com/cactus/go-camo
```

**Comment by cactus** [comment]
that is just a warning. go get should still have checked out the code.

**Comment by viraptor** [comment]
You're right - I assumed it was an error and didn't even check if it compiles. (It does)

**Comment by cactus** [comment]
Thanks for the report. 👍 
I updated the readme to hopefully help prevent anyone from running into the same issue.
