### ISSUE TITLE
Responsible Vulnerability Disclosure

### ISSUE THREAD

**Issue by dappelt** [cactus/go-camo#35]
### Specifications

Version: go-camo 1.1.4
Platform: Any

### Behavior

I would like to report a security vulnerability in go-camo. Is there a prefered (and confidentially) way of receiving more details?

**Comment by cactus** [comment]
@dappelt Thanks for reaching out!

I have a wire account (`@ixephus`), if that meets your requirements for secure/confidential information exchange. If not, let me know if you have any suggestions for alternatives.

Note: Alas, I seldom use the wire account (not many people I chat with regularly on there yet), so dropping a message like this is probably the best way to get me to check it.

**Comment by jacobbednarz** [comment]
Side note: @cactus do you intend to use GitHub's [maintainer security advisories](https://help.github.com/en/articles/about-maintainer-security-advisories) for this type of thing? As you can also establish a policy in there too which would help this type of discussion.

**Comment by cactus** [comment]
@jacobbednarz Interesting. I didn't realize that advisories allowed for private collaboration. I'll definitely look into it!

**Comment by cactus** [comment]
@jacobbednarz thanks again for the heads up.

Status:
* created security policy page - https://github.com/cactus/go-camo/security/policy
* created a draft security advisory, and invited @dappelt to collaborate on it.

**Comment by jacobbednarz** [comment]
nice one! I've just confirmed I can't see it so you're secrets are safe for now 🙂

**Comment by dappelt** [comment]
> created a draft security advisory, and invited @dappelt to collaborate on it.

Perfect, I provided more information on the draft.

**Comment by cactus** [comment]
Yeah, these look like valid issues. Working on fixes.

**Comment by cactus** [comment]
Security advisory has been [published](https://github.com/cactus/go-camo/security/advisories/GHSA-xrmp-4542-q746).

**Comment by cactus** [comment]
Release v1.1.5 builds are [up now](https://github.com/cactus/go-camo/releases/tag/v1.1.5).
