### ISSUE TITLE
Content-Type validation bypass (née Responsible Disclosure)

### ISSUE THREAD

**Issue by dappelt** [cactus/go-camo#46]
I would like to report a security vulnerability. Can you please create a Draft Security Advisory?

**Comment by cactus** [comment]
Will do. Thanks!

**Comment by cactus** [comment]
Draft advisory created, and @dappelt invited to collaborate on it.

**Comment by cactus** [comment]
This advisory has been accepted. 
**Status**: Working on a fix.

**Comment by cactus** [comment]
**status**: release planned for tomorrow.

**Comment by cactus** [comment]
[v2.1.1](https://github.com/cactus/go-camo/releases/tag/v2.1.1) released with fixes.

**Comment by cactus** [comment]
Advisory published: https://github.com/cactus/go-camo/security/advisories/GHSA-jg2r-qf99-4wvr
Please upgrade your installs!

**Comment by cactus** [comment]
Thanks to @dappelt for the report, and assistance with the fix review.

**Comment by dappelt** [comment]
Thanks for dealing with the issue so quickly.
