### ISSUE TITLE
docker image on ghcr is missing

### ISSUE THREAD

**Issue by viceice** [cactus/go-camo#73]
### Specifications

not relevant

### Expected Behavior

to find the docker images on ghcr.io

### Actual Behavior

the link from the readme points to a non existing page 

### Steps to reproduce

1. go to https://github.com/cactus/go-camo?tab=readme-ov-file#containers
2. click on `github packages` link

**Comment by dropwhile** [comment]
Thanks for the report! Looks like it was a github permissions issue (the package was there, but not public).
It should be visible now.

**Comment by viceice** [comment]
thanks 🙏
