### ISSUE TITLE
publishing of container images for release 2.4.11 failed

### ISSUE THREAD

**Issue by SISheogorath** [cactus/go-camo#78]
It seems like the publish steps for the 2.4.11 release failed for both ghcr and docker:

https://github.com/cactus/go-camo/actions/runs/8548730031
https://github.com/cactus/go-camo/actions/runs/8548730029

Would be nice if this could be fixed.

**Comment by dropwhile** [comment]
@SISheogorath should be fixed now. 
Thanks for the reporting the issue!
