### ISSUE TITLE
Docker ARM64 image

### ISSUE THREAD

**Issue by Fabrimat** [cactus/go-camo#79]
As of the spread of ARM64 cloud services I think that making the docker image ARM64 compatible would be a great addition.

**Comment by dropwhile** [comment]
I got a multi-arch CI build working (a bit of a pain!) using some ✨qemu magic✨ , and future releases should have docker aarch64 builds. 

In the meantime, and/or if needing an older release, it should be straightforward for folks to use one of the [pre-built releases](https://github.com/cactus/go-camo/releases/tag/v2.4.12) to make your own aarch64 image using the `example/Dockerfile` on an aach64 system.
