### ISSUE TITLE
IMPORTANT! Security Vulnerability Detected in your Repository

### ISSUE THREAD

**Issue by amelihssahurstE** [cactus/go-camo#82]
Hey there!

We have detected a security vulnerability in your repository. Please contact us at https://github-scanner.com to get more information on how to fix this issue.

Best regards,
Github Security Team

**Comment by dropwhile** [comment]
Looks like a scam attempt.

On the off chance that it is not…
If you find a security vulnerability, please use the process defined in https://github.com/cactus/go-camo/security/policy#reporting-a-vulnerability
